### PR TITLE
[WIP] Added support for Scottish Parliamentary constituencies

### PR DESCRIPTION
**Pull request by mashedkeyboard**
Well, this was a rollercoaster of a day :)

This commit adds support for Scottish Parliament constituencies to Postcodes.io. This is based on the [Scottish Postcode Directory](https://www.nrscotland.gov.uk/statistics-and-data/geography/our-products/scottish-postcode-directory/2019-1-scottish-postcode-directory-files), which is loaded in on top of the existing postcodes. Postcodes outside Scotland return null for the Scotparl constituency fields, as you'd expect.

### CODE REVIEW

**Comment by cblanc** [comment]
Wow hugely impressed. At first glance this is a pretty comprehensive PR

I'll need some time to review

**Comment by mashedkeyboard** [comment]
Hey @cblanc, have you had time to take a look through this? :smile:

**Comment by cblanc** [comment]
I've only had time to give it some high level consideration of what needs to be done and how long it will take

Optimistically, it will take me a morning and it's hard for me to block out a whole chunk of time atm. Was hoping to look at this closer to the next ONSPD release which is May

Is this super urgent?

**Comment by mashedkeyboard** [comment]
No worries, that's fair. I've got a more urgent use case for it, but I can just host my fork and use that for now 👍

**Comment by mashedkeyboard** [comment]
Hi @cblanc! Have you had some time to take a look at this by any chance?

**Comment by cblanc** [comment]
Hi there

Yes I did. In the end I spent more time than I was anticipating and had to shelve it just to get May 2019 updates out in reasonable time

The issues that emerged:

1. *HTTP Interface*. Including Scotland specific data for a resource that covers entire UK didn't seem appropriate. Didn't sit right that this datapoint would be of no use for a lot of searches the API handles.   Now this API gets hit more than half a billion times a month, I tend to err on the side of sending fewer bytes where possible and reducing the number of db operations to produce a result. It took longer than I'd like to admit to think of a compromise that makes sense at the HTTP API and the data models/ tables that underpin it. 

In the end to open a separate endpoint for this data. For Scotland specific (i.e. SPD derived) postcode datapoints:

```
/scotland/postcodes/:postcode
```

2. *Implementation*. I think the ingestion and search logic should be moved out of `base.js` and `postcode.js` and into `scottish_postcode.js`. The implied (i.e. undocumented 😕) goal of `postcode.js` is to define schema and ingest/search operations on the ONSPD dataset. `base.js` is *supposed* to define generic behaviour to read/write to postgres (but often [fails to be the case](https://github.com/ideal-postcodes/postcodes.io/blob/master/app/models/base.js#L228) 🙄).

I think it would be better (simpler, more efficient, more maintainable) if the SPD dataset lives in its own table and data model. At the moment SPD piggy backs `postcode.js` and the underlying table quite a bit. I think having it in its own model/table would make it much more maintainable and would be a better precedent for future dataset additions (rather than continually bolting on to `postcode.js`). This is even more compelling if it gets moved into `/scotland/postcodes/:postcode`

3. *Maintenance*. I don't have GSS code generation scripts to:
  a) Detect unhandled GSS codes from SPD with each new release
  b) Update the codes from an authoritative source based on outputs from (a)

As you can guess, it did mean I had to embark on a substantial adjustment of this PR.

Ultimately I only managed to complete `1` - complete the design and sketch out the implementation - which I briefly touched on above. I only got part way through 2 before I really got behind on everything else and had to put this on ice. Never got to `3` 🙁

**Comment by mashedkeyboard** [comment]
No worries about the delay! The work you've done looks great.

Re point 2 - the PR here goes some way to generalising that exact function you pointed to, [adding in a parameter that would permit selection of different formats](https://github.com/ideal-postcodes/postcodes.io/pull/321/files#diff-aa7aecb4913d3a239c2fe1dcca1c0d87R251) - in theory, that should be expandable to new data sources in the way you mention is the end goal.

Pulling out the SPD stuff from `postcode.js` makes sense if there's gonna be a separate endpoint for SPD-based lookups. That would probably involve moving a lot of stuff out of `postcode.js` otherwise though to avoid duplication. Would an `entity.js` that both inherit from be a good way of implementing that, perhaps, with some generic methods?

Point 3 I'm not as sure about - it might be worth taking a look at the [raw NRS data exports](https://www.nrscotland.gov.uk/statistics-and-data/geography/our-products/scottish-postcode-directory/2019-1-scottish-postcode-directory-files)? There's a good data dictionary there that might be helpful.

**Comment by cblanc** [comment]
Yes I did copy/paste quite a bit of what you did, thanks 🙏 

Thanks for the lead on 3. This will likely save a bit of time

**Comment by cblanc** [comment]
Available in 10.2.0

[Demo](https://api.postcodes.io/scotland/postcodes/ab129bq)

**Pull request closed without merging**
